export const FETCH_USER_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USERS_FAILURE";
export const UPDATE_USER_REQUEST = "UPDATE_USERS_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USERS_FAILURE";
